function resolveSiteUrl(): string {
  return (
    process.env.NEXT_PUBLIC_SITE_URL ??
    process.env.NEXT_PUBLIC_APP_URL ??
    (process.env.NODE_ENV === "production"
      ? "https://maidlinx.com"
      : "http://localhost:3001")
  );
}

export const siteConfig = {
  name: "MaidLinx",
  description:
    "Book cleaning on demand in Toronto/GTA and South Florida. Enter your address, pick a service and time, and confirm online.",
  url: resolveSiteUrl(),
  /** App Router file convention: `src/app/opengraph-image.tsx` (1200×630). */
  ogImage: "/opengraph-image",
  links: {
    support: "mailto:support@maidlinx.com",
    help: "/#faq",
  },
} as const;

export const routes = {
  home: "/",
  services: "/services",
  howItWorks: "/how-it-works",
  forBusiness: "/for-business",
  reviews: "/reviews",
  about: "/about",
  signIn: "/sign-in",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  account: "/account",
  book: "/book",
  bookAddress: "/book/address",
  bookProperty: "/book/property",
  bookDetails: "/book/details",
  bookService: "/book/service",
  bookExtras: "/book/addons",
  bookAddons: "/book/addons",
  bookSchedule: "/book/date",
  bookDate: "/book/date",
  bookTime: "/book/time",
  bookAccess: "/book/access",
  bookReview: "/book/review",
  bookPayment: "/book/payment",
  bookConfirmation: (id: string) => `/book/confirmation/${id}`,
  bookingStatus: (id: string) => `/booking/${id}`,
  earn: "/earn",
  becomeCleaner: "/earn",
  dashboard: "/dashboard",
  dashboardBookings: "/dashboard/bookings",
  dashboardInvoices: "/dashboard/invoices",
  dashboardReceipts: "/dashboard/receipts",
  dashboardFavorites: "/dashboard/favorites",
  dashboardProfile: "/dashboard/profile",
  dashboardSavedPlaces: "/dashboard/saved-places",
  dashboardNotifications: "/dashboard/notifications",
  proHome: "/pro/home",
  proDashboard: "/pro",
  proJobs: "/pro/jobs",
  proSchedule: "/pro/schedule",
  proEarnings: "/pro/earnings",
  proRatings: "/pro/ratings",
  proAvailability: "/pro/availability",
  proProfile: "/pro/profile",
  proOnboarding: "/pro/onboarding",
  proDocuments: "/pro/documents",
  proJob: (id: string) => `/pro/jobs/${id}`,
  cleanerDashboard: "/pro/home",
  cleanerJobs: "/pro/jobs",
  cleanerSchedule: "/pro/schedule",
  cleanerEarnings: "/pro/earnings",
  cleanerRatings: "/pro/ratings",
  cleanerAvailability: "/pro/availability",
  cleanerProfile: "/pro/profile",
  cleanerSettings: "/pro/settings",
  cleanerOnboarding: "/pro/onboarding",
  cleanerDocuments: "/pro/documents",
  cleanerJob: (id: string) => `/pro/jobs/${id}`,
  proSettings: "/pro/settings",
  admin: "/admin",
  adminBookings: "/admin/bookings",
  adminCustomers: "/admin/customers",
  adminCleaners: "/admin/cleaners",
  adminServices: "/admin/services",
  adminMarkets: "/admin/markets",
  adminServiceZones: "/admin/service-zones",
  adminPricing: "/admin/pricing",
  adminAssignments: "/admin/assignments",
  adminPayments: "/admin/payments",
  adminReviews: "/admin/reviews",
  adminSupport: "/admin/support",
  adminRevenue: "/admin/revenue",
  adminAnalytics: "/admin/analytics",
  adminCoupons: "/admin/coupons",
  adminServiceAreas: "/admin/service-areas",
  adminDisputes: "/admin/disputes",
  adminRefunds: "/admin/refunds",
  adminPayouts: "/admin/payouts",
  adminLogs: "/admin/logs",
  adminPermissions: "/admin/permissions",
  adminAudit: "/admin/audit",
  profile: "/dashboard/profile",
  legal: {
    privacy: "/legal/privacy",
    terms: "/legal/terms",
    cleanerAgreement: "/legal/cleaner-agreement",
  },
} as const;
