export const siteConfig = {
  name: "MaidLinx",
  description:
    "Book cleaning on demand in Toronto/GTA and South Florida. Enter your address, pick a service and time, and confirm online.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  ogImage: "/brand/maidlinx-logo.png",
  links: {
    support: "mailto:support@maidlinx.com",
    help: "/#faq",
  },
} as const;

export const routes = {
  home: "/",
  services: "/services",
  howItWorks: "/how-it-works",
  forBusiness: "/for-business",
  reviews: "/reviews",
  about: "/about",
  signIn: "/sign-in",
  signUp: "/sign-up",
  book: "/book",
  bookAddress: "/book/address",
  bookProperty: "/book/property",
  bookDetails: "/book/details",
  bookService: "/book/service",
  bookExtras: "/book/addons",
  bookAddons: "/book/addons",
  bookSchedule: "/book/date",
  bookDate: "/book/date",
  bookTime: "/book/time",
  bookAccess: "/book/access",
  bookReview: "/book/review",
  bookPayment: "/book/payment",
  bookConfirmation: (id: string) => `/book/confirmation/${id}`,
  bookingStatus: (id: string) => `/booking/${id}`,
  earn: "/earn",
  becomeCleaner: "/earn",
  dashboard: "/dashboard",
  dashboardBookings: "/dashboard/bookings",
  dashboardInvoices: "/dashboard/invoices",
  dashboardReceipts: "/dashboard/receipts",
  dashboardFavorites: "/dashboard/favorites",
  dashboardProfile: "/dashboard/profile",
  dashboardSavedPlaces: "/dashboard/saved-places",
  dashboardNotifications: "/dashboard/notifications",
  proDashboard: "/cleaner",
  proJobs: "/cleaner/jobs",
  proSchedule: "/cleaner/schedule",
  proEarnings: "/cleaner/earnings",
  proRatings: "/cleaner/ratings",
  proAvailability: "/cleaner/availability",
  proProfile: "/cleaner/profile",
  proOnboarding: "/cleaner/onboarding",
  proDocuments: "/cleaner/documents",
  proJob: (id: string) => `/cleaner/jobs/${id}`,
  cleanerDashboard: "/cleaner",
  cleanerJobs: "/cleaner/jobs",
  cleanerSchedule: "/cleaner/schedule",
  cleanerEarnings: "/cleaner/earnings",
  cleanerRatings: "/cleaner/ratings",
  cleanerAvailability: "/cleaner/availability",
  cleanerProfile: "/cleaner/profile",
  cleanerSettings: "/cleaner/settings",
  cleanerOnboarding: "/cleaner/onboarding",
  cleanerDocuments: "/cleaner/documents",
  cleanerJob: (id: string) => `/cleaner/jobs/${id}`,
  proSettings: "/cleaner/settings",
  admin: "/admin",
  adminBookings: "/admin/bookings",
  adminCustomers: "/admin/customers",
  adminCleaners: "/admin/cleaners",
  adminServices: "/admin/services",
  adminMarkets: "/admin/markets",
  adminServiceZones: "/admin/service-zones",
  adminPricing: "/admin/pricing",
  adminAssignments: "/admin/assignments",
  adminPayments: "/admin/payments",
  adminReviews: "/admin/reviews",
  adminSupport: "/admin/support",
  adminRevenue: "/admin/revenue",
  adminAnalytics: "/admin/analytics",
  adminCoupons: "/admin/coupons",
  adminServiceAreas: "/admin/service-areas",
  adminDisputes: "/admin/disputes",
  adminRefunds: "/admin/refunds",
  adminPayouts: "/admin/payouts",
  adminLogs: "/admin/logs",
  adminPermissions: "/admin/permissions",
  adminAudit: "/admin/audit",
  profile: "/dashboard/profile",
  legal: {
    privacy: "/legal/privacy",
    terms: "/legal/terms",
    cleanerAgreement: "/legal/cleaner-agreement",
  },
} as const;
